### ISSUE TITLE
[No such file or directory] \output/NoGoodbye/htdemucs/NoGoodbye/drums.wav

### ISSUE THREAD

**Issue by VLTNOgithub** [axeldelafosse/stemgen#43]
### INFORMATION
**OS:** Windows 10
**Running In:** Powershell
**Command:** `python stemgen.py -i NoGoodbye.flac`

### MORE
I've install all requirements. It starts converting `\output/NoGoodbye/htdemucs/NoGoodbye/drums.wav` to ALAC and I get the following error: `C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/htdemucs/NoGoodbye/drums.wav: No such file or directory`.
FLAC file plays fine.

### LOG
```
Using CPU for processing.
Output dir already exists.
Working dir created.
Done.
Extracting bit depth...
bits_per_sample=16
Done.
Extracting sample rate...
sample_rate=44100
Done.
Extracting cover...
ffmpeg version 2023-04-12-git-1179bb703e-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  6.100 / 58.  6.100
  libavcodec     60.  9.100 / 60.  9.100
  libavformat    60.  4.101 / 60.  4.101
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, flac, from 'C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/NoGoodbye.flac':
  Metadata:
    TITLE           : No Goodbye
    ARTIST          : Paul Kalkbrenner
    ALBUM           : No Goodbye
    YEAR            : 2019
    DATE            : 2019-07-26
  Duration: 00:06:30.92, start: 0.000000, bitrate: 840 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
  Stream #0:1: Video: mjpeg (Progressive), yuvj444p(pc, bt470bg/unknown/unknown), 500x500 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
Output #0, image2, to 'C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/cover.jpg':
  Metadata:
    TITLE           : No Goodbye
    ARTIST          : Paul Kalkbrenner
    ALBUM           : No Goodbye
    YEAR            : 2019
    DATE            : 2019-07-26
    encoder         : Lavf60.4.101
  Stream #0:0: Video: mjpeg (Progressive), yuvj444p(pc, bt470bg/unknown/unknown), 500x500 [SAR 300:300 DAR 1:1], q=2-31, 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Press [q] to stop, [?] for help
[image2 @ 000001dd017d18c0] The specified filename 'C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/cover.jpg' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 000001dd017d18c0] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
frame=    1 fps=0.0 q=-1.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
video:42kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Cover extracted with ffmpeg.
Done.
Extracting metadata...
TITLE=No Goodbye
ARTIST=Paul Kalkbrenner
ALBUM=No Goodbye
YEAR=2019
DATE=2019-07-26
{'title': 'No Goodbye', 'artist': 'Paul Kalkbrenner', 'album': 'No Goodbye', 'year': '2019-07-26', 'cover': 'C:\\Users\\NZXT\\Downloads\\stemgen-master\\output\\NoGoodbye\\cover.jpg'}
Creating tags.json...
Done.
Converting to wav and/or downsampling...

Input File     : 'C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/NoGoodbye.flac'
Channels       : 2
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:06:30.92 = 17239572 samples = 29319 CDDA sectors
File Size      : 41.0M
Bit Rate       : 840k
Sample Encoding: 16-bit FLAC
Comments       :
TITLE=No Goodbye
ARTIST=Paul Kalkbrenner
ALBUM=No Goodbye
YEAR=2019
DATE=2019-07-26

In:100%  00:06:30.92 [00:00:00.00] Out:17.2M [!=====|=====!] Hd:0.1 Clip:0
Done.
Done.
Ready!
Creating a Stem file for NoGoodbye...
Splitting stems...
Using 16-bit model...
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\NZXT\Downloads\stemgen-master\output\NoGoodbye\htdemucs
Separating track C:\Users\NZXT\Downloads\stemgen-master\output\NoGoodbye\NoGoodbye.flac
100%|██████████████████████████████████████████████████████████████████████| 391.95/391.95 [04:37<00:00,  1.41seconds/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python311\Lib\site-packages\demucs\__main__.py", line 10, in <module>
    main()
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python311\Lib\site-packages\demucs\separate.py", line 199, in main
    save_audio(source, str(stem), **kwargs)
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python311\Lib\site-packages\demucs\audio.py", line 260, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate,
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchaudio\_backend\utils.py", line 312, in save
    backend = dispatcher(uri, format, backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NZXT\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchaudio\_backend\utils.py", line 222, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri C:\Users\NZXT\Downloads\stemgen-master\output\NoGoodbye\htdemucs\NoGoodbye\drums.wav and format None.
Done.
Creating stem...

[Done 0/6]


converting C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/NoGoodbye.wav to alac...
ffmpeg version 2023-04-12-git-1179bb703e-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  6.100 / 58.  6.100
  libavcodec     60.  9.100 / 60.  9.100
  libavformat    60.  4.101 / 60.  4.101
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[aist#0:0/pcm_s16le @ 0000023e1c4a6b80] Guessed Channel Layout: stereo
Input #0, wav, from 'C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/NoGoodbye.wav':
  Duration: 00:06:30.92, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> alac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to 'C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/NoGoodbye.m4a':
  Metadata:
    encoder         : Lavf60.4.101
  Stream #0:0: Audio: alac (alac / 0x63616C61), 44100 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc60.9.100 alac
size=   40218kB time=00:06:30.83 bitrate= 843.0kbits/s speed= 107x
video:0kB audio:40201kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.044139%

[Done 1/6]


converting C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/htdemucs/NoGoodbye/drums.wav to alac...
ffmpeg version 2023-04-12-git-1179bb703e-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  6.100 / 58.  6.100
  libavcodec     60.  9.100 / 60.  9.100
  libavformat    60.  4.101 / 60.  4.101
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
C:\Users\NZXT\Downloads\stemgen-master\output/NoGoodbye/htdemucs/NoGoodbye/drums.wav: No such file or directory
Command '['ffmpeg', '-i', 'C:\\Users\\NZXT\\Downloads\\stemgen-master\\output/NoGoodbye/htdemucs/NoGoodbye/drums.wav', '-c:a', 'alac', '-c:v', 'copy', 'C:\\Users\\NZXT\\Downloads\\stemgen-master\\output/NoGoodbye/htdemucs/NoGoodbye/drums.m4a']' returned non-zero exit status 1.
Done.
Cleaning...
Done.
Success! Have fun :)
```

**Comment by Scar2201** [comment]
This issue is related to demucs. There is an open issue on their git ( https://github.com/facebookresearch/demucs/issues/570 ). The easiest way to solve that is to install soundfile `pip install soundfile`
